[package]
name = "photo-turntable"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
btleplug = "0.11.8"
eframe = "0.31.1"
egui_double_slider = "0.7.1"
gphoto2 = "3.4.1"
tokio = { version = "1.45.1", features = ["full", "time"] }
uuid = { version = "1.17.0", features = ["v4"] }
